# Generated by Django 3.1.4 on 2020-12-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_auto_20201208_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
